$BuildRequestedFor = $env:BUILD_REQUESTEDFOR
$BuildSourceVersionMessage = $env:BUILD_SOURCEVERSIONMESSAGE

Write-Host "BuildRequestedFor: $BuildRequestedFor"
Write-Host "BuildSourceVersionMessage: $BuildSourceVersionMessage"

If ($BuildRequestedFor -eq 'Automated Build User' -and $BuildSourceVersionMessage.Contains("***NO_CI***")) {
    # Skips the remaining build steps
    Write-Host "Skipping the remaining builds because this build was triggered on a schedule, and the current changeset was generated by a previous QA Deploy build."
    Write-Host "##vso[task.setvariable variable=agent.jobstatus;]canceled"
    Write-Host "##vso[task.complete result=Canceled;]DONE"
}
